### ISSUE TITLE
Add homebrew recipe for buildifier

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/buildifier#48]
It would be great to be able to install buildifier via Homebrew.

**Comment by pmbethe09** [comment]
Sounds good to me.  Are you volunteering?

**Comment by dpursehouse** [comment]
This seems to have been done.  I just updated homebrew and buildifier was available.

**Comment by davidzchen** [comment]
Indeed it has: Homebrew/homebrew-core#10325

**Comment by dpursehouse** [comment]
It seems there is a problem with the homebrew packaging of buildifier.

See the discussion on this PR where I was trying to fix the version string: https://github.com/Homebrew/homebrew-core/pull/12413

Apparently downloading pre-built Go binaries rather than depending on the brew go formula is a violation of the homebrew packaging guidelines.
